### ISSUE TITLE
ansible-galaxy install ansible-role-govc

### ISSUE THREAD

**Issue by ENGAT** [vmware/ansible-role-govc#8] opened 2018-11-07 19:57 UTC
ansible-galaxy install ansible-role-govc

Creates and error:
- downloading role 'ansible-role-govc', owned by 
 [WARNING]: - ansible-role-govc was NOT installed successfully: Content has no field named 'owner'

**Comment by tompscanlan** [comment] 2018-11-09 22:51
Thanks for the issue!

I think this was caused by an issue in ansible-galaxy.  I see other bugs in the wild where roles with "-" were swapped to "_", and showing a similar error.  

I confirm the failure was happening.  After kicking off a new build, the install works as expected. Closing.

**Closed as completed by tompscanlan** 2018-11-09 22:51 UTC
